### ISSUE TITLE
Failing tests on Windows systems

### ISSUE THREAD

**Issue by ramananbalakrishnan** [reneeb/Perl-Critic-OTRS#3]
Hi, I am working on this distribution for my CPAN PR challenge during January. 

It has been reported through http://matrix.cpantesters.org/?dist=Perl-Critic-OTRS;os=mswin32;reports=1 that this distribution fails test 09_prohibit_core_functions.t on Windows systems. 

After doing some research, I noticed that the failure reported as 
`dmake.EXE:  Error code 255, while making 'test_dynamic'`
is also seen in a few other modules [[1]](https://github.com/bigpresh/Dancer-Plugin-Database/issues/35), [[2]](https://rt.cpan.org/Public/Bug/Display.html?id=95636).

The error seems to be a result of the testing conditions, rather than the distribution itself. The solution seems to be either remove conflicting perl installations [[3]](https://github.com/bigpresh/Dancer-Plugin-Database/issues/35#issuecomment-9198219) or just skipping this test when detecting a Win32 OS [[4]](https://github.com/autarch/DateTime-TimeZone/commit/73e1cad2b25f1d317be76f9539f80c2fbe25fa01#diff-311e0a07da9925c2b4270e39f68719f6). 

I could send in a pull request making the required change (i.e. skip on Win32) to t/09_prohibit_core_functions.t

**Comment by reneeb** [comment]
Hi,

thanks for investigating the issue. I had no idea what the cause could be. I would be grateful if you could send a PR where the tests are skipped on Windows.

- Renée
